# wrangler.toml
name = 'myth'
main = "_worker.js"
compatibility_date = "2025-11-04"
keep_vars = true

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1

[[kv_namespaces]]
binding = "KV"      
id = "9f8043ebf6454041a27cd7b940747c5e"
